version: '3'
services:
  minio:
    image: minio/minio
    command: ['server', '/data', '--console-address', ':9001'] # --console-address オプションの追加
    ports:
      - 9000:9000
      - 9001:9001 # コンソール用のポートフォワード設定追加
    environment:
      MINIO_ROOT_USER: minio            # 元 MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: miniosecret  # 元 MINIO_SECRET_KEY

    
      